coin_type: "btc"

# 程序本地转发地址
local_addr: ":10010"

# 远程代理地址，常用地址（E池/鱼池/币印等）已经内置 SSL/TCP 判断
remote_addr: "f2miner.tk:3333"


# 开启性能模式：解除 ulimit -n 1024 限制
enable_performance_mode: true


# 日志输出位置, 目前日志是加密存储，格式为 *.xlog
# 如果在程序使用过程中出现异常情况，请将日志提交给开发者进行排查
# 请尽量使用绝对路径
log_dir: "/tmp"

# 详细日志采样级别，用于开发者排查问题使用, 日常使用建议设置为 0
# 0: 不开启详细日志采样
# 1: 记录 0.1% 日志采样
# 2: 记录 1% 日志采样
# 3: 全量日志记录，当机器数量超过 50 时候，当心磁盘存不下
log_sampling_level: 0

# DNS 服务器地址：避免 DNS 污染，请使用安全/可访问通的 DNS 地址
# 默认：8.8.8.8, 8.8.4.4
dns_server: "8.8.8.8, 8.8.4.4"

# 临时 block 掉出问题的 IP
# 在使用过程中，发现有些场景下会出现后端可达但是不可使用的场景：
#  DNS 返回的地址，可以访问通，但是无法正常使用）
# 当出现此类场景后，请添加对应 IP 至此
block_ips: ""

# DNS 解析重试次数
# 当通过 dnsServer 解析到对应后端地址后，proxy 会尝试与其建立 TLS/TCP 连接
# 如果 1s 内无法建立成功，则判断当前后端不可达
# 随后将重新向 DNS 发起解析请求
# 默认重试 10 次，超过重试次数后，服务会退出
dns_retry_times: 10

# IP可连接性校验时长（单位：秒）
# 目前会校验矿池 IP 的可连接性，如规定时间内未能成功连接，则认为该 IP 不可用
# 默认 1s，0 表示不校验
dns_ip_verify_seconds: 1


enable_reject_checker_v2: false
enable_reject_checker_v1: false

